# Generated by Django 3.2.16 on 2022-11-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('majorName', models.TextField(default='대학 학과공통')),
                ('grade', models.TextField(default='')),
                ('credit', models.TextField(default='')),
                ('subjectName', models.TextField(default='')),
                ('subjectNumber', models.TextField(default='')),
                ('classNumber', models.TextField(default='')),
                ('professorName', models.TextField(default='')),
                ('limitNumber', models.TextField(default='0')),
                ('currentNumber', models.TextField(default='')),
            ],
        ),
    ]
