# Generated by Django 3.2.16 on 2022-11-18 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseNumber', models.TextField(primary_key=True, serialize=False)),
                ('subjectName', models.TextField()),
                ('majorName', models.TextField()),
                ('grade', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('professorName', models.TextField()),
                ('limitNumber', models.IntegerField()),
                ('currentNumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentNumber', models.TextField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('grade', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('majorName', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplyCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrolment.course')),
                ('studentNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrolment.student')),
            ],
        ),
    ]
